development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: searchengine_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:

        # Change the default write concern. (default = { w: 1 })
        
  options:
    raise_not_found_error: false
    # Includes the root model name in json serialization. (default: false)
    
test:
  clients:
    default:
      database: searchengine_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
